### ISSUE TITLE
Sonarcloud does not analyze code

### ISSUE THREAD

**Issue by vonfredd** [Ebyrdeu/movie_jakarta#15]
### Describe the bug
Sonarcloud does not analyze the code. According to [docs](https://docs.sonarsource.com/sonarcloud/enriching/test-coverage/java-test-coverage/) the analyzing is done with a third party tool that needs to be included in the pom.xml.

### To Reproduce
1. Make changes in project
2. Push to github repository
3. Let sonarcloud analyze

### Expected behavior
Sonarcloud should show a result of code coverage

**Comment by ValentinaSukonina** [comment]
Missing plugins in pom.xml (jacoco and maven-surefire-plugin). pom.xml will be updated with next merge of pull request "13 create dto class #12"
