### ISSUE TITLE
Create MovieRepository class

### ISSUE THREAD

**Issue by vonfredd** [Ebyrdeu/movie_jakarta#20]
### Problem Description
When we have a database connection we want to be able to talk to the database with queries or to persist entities. 
A MovieRepository class would be a good way of handling it.

**Comment by ajohnsson95** [comment]
https://github.com/Ebyrdeu/movie_jakarta/pull/24/commits/2d3f317383e613cab20122a393ef431882aa23b2 new update on MovieRepository
